models:
    - name: edsr3
      launchers:
          framework: dlsdk
          adapter: super_resolution
      datasets:
      - name: DIV2K_bicubic_x2
        reader:
            type: opencv_imread
            reading_flag: gray
        preprocessing:
          - type: corner_crop
            dst_width: 640
            dst_height: 360
          - type: normalization
            std: 255
        postprocessing:
          - type: corner_crop_image
            dst_width: 1280
            dst_height: 720
            apply_to: annotation
          - type: rgb_to_gray
        metrics:
            - type: psnr
              presenter: print_vector